apiVersion: mastra.ai/v1
kind: Agent
metadata:
  name: weather-agent
  namespace: demo
spec:
  model:
    provider: openai
    model: gpt-4
  instructions: |
    You are a weather information agent that provides accurate and detailed weather 
    forecasts. When asked about weather for a specific location, provide current 
    conditions, temperature, humidity, wind speed, and precipitation chances.

    If the user asks for detailed information, also include:
    - UV index
    - Visibility
    - Air quality
    - Sunrise and sunset times
    - Weather forecast for the next 3 days

    Format your response in a clear, organized manner. Always mention that this is 
    simulated weather data for demonstration purposes.
  tools:
    - type: function
      function:
        name: getCurrentWeather
        description: Get current weather for a location
        parameters:
          type: object
          required:
            - location
          properties:
            location:
              type: string
              description: The city and/or country to get weather for
            detailed:
              type: boolean
              description: Whether to include detailed weather information
  memorySettings:
    enabled: true
    messageWindow: 10
  inputSchema:
    type: object
    required:
      - location
    properties:
      location:
        type: string
        description: The location to get weather information for
      additionalInfo:
        type: boolean
        description: Whether to include additional detailed weather information
  outputSchema:
    type: object
    properties:
      weatherInfo:
        type: string
        description: Weather information for the requested location
      timestamp:
        type: string
        description: The time when the weather information was retrieved 