apiVersion: mastra/v1
kind: MastraPod
metadata:
  name: comprehensive-example
  namespace: default

# 全局提供者配置
providers:
  openai:
    apiKey: ${env.OPENAI_API_KEY}
  anthropic:
    apiKey: ${env.ANTHROPIC_API_KEY}

# 全局内存配置
memory:
  type: ephemeral
  config:
    ttl: 3600

# 日志配置
logging:
  level: info
  format: json

# 资源定义
resources:
  # 工具定义
  - apiVersion: mastra/v1
    kind: Tool
    metadata:
      name: web-search-tool
      namespace: default
    spec:
      id: web-search
      name: "Web Search Tool"
      description: "Search the web for information on a given topic"
      type: function
      execute: |
        async function webSearch(params) {
          const { query } = params;
          console.log(`[Web Search] 搜索: ${query}`);
          
          return {
            results: [
              { title: `关于${query}的资料1`, url: "https://example.com/1", snippet: `这是关于${query}的第一个结果...` },
              { title: `${query}的最新研究`, url: "https://example.com/2", snippet: `${query}的最新研究表明...` },
              { title: `${query}入门指南`, url: "https://example.com/3", snippet: `学习${query}的基础知识...` }
            ]
          };
        }

  - apiVersion: mastra/v1
    kind: Tool
    metadata:
      name: calculator-tool
      namespace: default
    spec:
      id: calculator
      name: "Calculator Tool"
      description: "执行基本算术运算"
      type: function
      execute: |
        function calculator(params) {
          const { operation, a, b } = params;
          let result;
          
          switch (operation) {
            case 'add':
              result = a + b;
              break;
            case 'subtract':
              result = a - b;
              break;
            case 'multiply':
              result = a * b;
              break;
            case 'divide':
              if (b === 0) throw new Error('除数不能为零');
              result = a / b;
              break;
            default:
              throw new Error('不支持的操作');
          }
          
          return { result };
        }

  - apiVersion: mastra/v1
    kind: Tool
    metadata:
      name: weather-tool
      namespace: default
    spec:
      id: weather
      name: "Weather Tool"
      description: "获取指定位置的天气信息"
      type: function
      execute: |
        function weather(params) {
          const { location } = params;
          console.log(`[Weather] 获取${location}的天气`);
          
          // 模拟天气数据
          const conditions = ['晴朗', '多云', '小雨', '大雨', '雷雨', '大风'];
          const temperatures = Array.from({ length: 10 }, (_, i) => 20 + i);
          
          const randomCondition = conditions[Math.floor(Math.random() * conditions.length)];
          const randomTemperature = temperatures[Math.floor(Math.random() * temperatures.length)];
          
          return {
            location,
            condition: randomCondition,
            temperature: randomTemperature,
            unit: 'celsius',
            timestamp: new Date().toISOString()
          };
        }

  - apiVersion: mastra/v1
    kind: Tool
    metadata:
      name: news-tool
      namespace: default
    spec:
      id: news
      name: "News Tool"
      description: "获取指定主题的最新新闻"
      type: function
      execute: |
        function news(params) {
          const { topic, count = 3 } = params;
          console.log(`[News] 搜索关于${topic}的新闻`);
          
          // 模拟新闻数据
          const news = [];
          for (let i = 0; i < count; i++) {
            news.push({
              title: `${topic}领域的重大突破 ${i + 1}`,
              source: `新闻来源 ${i + 1}`,
              date: new Date().toISOString(),
              summary: `这是关于${topic}的一条模拟新闻摘要...`
            });
          }
          
          return { news };
        }

  # 代理定义
  - apiVersion: mastra/v1
    kind: Agent
    metadata:
      name: research-agent
      namespace: default
    spec:
      id: research-agent
      name: "Research Agent"
      description: "研究助手，帮助用户查找和整理信息"
      instructions: |
        你是一个研究助手，专长于帮助用户查找和整理信息。
        你可以使用搜索工具查找信息，并提供简洁明了的摘要。
        请保持客观，并确保提供的信息是基于事实的。
      model:
        provider: openai
        name: gpt-4
        parameters:
          temperature: 0.2
          max_tokens: 500
      tools:
        web-search: web-search-tool
        news: news-tool
      memory:
        enabled: true
        type: ephemeral
        ttl: 3600

  - apiVersion: mastra/v1
    kind: Agent
    metadata:
      name: math-agent
      namespace: default
    spec:
      id: math-agent
      name: "Math Agent"
      description: "数学助手，帮助解决数学问题"
      instructions: |
        你是一个数学助手，专长于帮助用户解决数学问题。
        你可以使用计算器工具进行运算，并解释计算过程。
        请尽量详细地解释解题思路，以帮助用户理解。
      model:
        provider: openai
        name: gpt-4
        parameters:
          temperature: 0.1
          max_tokens: 500
      tools:
        calculator: calculator-tool
      memory:
        enabled: true
        type: ephemeral
        ttl: 3600

  - apiVersion: mastra/v1
    kind: Agent
    metadata:
      name: travel-agent
      namespace: default
    spec:
      id: travel-agent
      name: "Travel Agent"
      description: "旅行助手，提供旅行建议和信息"
      instructions: |
        你是一个旅行助手，专长于提供旅行建议和信息。
        你可以使用天气工具查询目的地天气，并提供相应的建议。
        请根据用户的需求和当地情况，提供个性化的旅行建议。
      model:
        provider: anthropic
        name: claude-3-sonnet
        parameters:
          temperature: 0.3
          max_tokens: 800
      tools:
        weather: weather-tool
      memory:
        enabled: true
        type: ephemeral
        ttl: 3600

  - apiVersion: mastra/v1
    kind: Agent
    metadata:
      name: summary-agent
      namespace: default
    spec:
      id: summary-agent
      name: "Summary Agent"
      description: "摘要助手，帮助整合和总结信息"
      instructions: |
        你是一个摘要助手，专长于整合和总结信息。
        你需要将收到的多个来源的信息进行分析和总结，提取关键信息。
        请保持客观，并确保摘要简洁明了、结构清晰。
      model:
        provider: anthropic
        name: claude-3-sonnet
        parameters:
          temperature: 0.2
          max_tokens: 1000
      memory:
        enabled: true
        type: ephemeral
        ttl: 3600

  # 工作流定义
  - apiVersion: mastra/v1
    kind: Workflow
    metadata:
      name: research-workflow
      namespace: default
    spec:
      id: research-workflow
      name: "Research Workflow"
      description: "研究工作流，收集和总结特定主题的信息"
      initialStep: collect-search-results
      steps:
        - id: collect-search-results
          name: "收集搜索结果"
          agent: research-agent
          input:
            message: "请搜索关于{{ workflow.input.topic }}的信息，并提供初步分析。"
          next: collect-news

        - id: collect-news
          name: "收集新闻"
          agent: research-agent
          input:
            message: "请找出关于{{ workflow.input.topic }}的最新新闻，重点关注最近的发展。"
          next: summarize-information

        - id: summarize-information
          name: "总结信息"
          agent: summary-agent
          input:
            message: |
              请根据以下信息，总结关于{{ workflow.input.topic }}的关键要点：
              
              搜索结果：{{ step.collect-search-results.result }}
              
              新闻：{{ step.collect-news.result }}
          next: END

  - apiVersion: mastra/v1
    kind: Workflow
    metadata:
      name: travel-planning-workflow
      namespace: default
    spec:
      id: travel-planning-workflow
      name: "Travel Planning Workflow"
      description: "旅行规划工作流，提供旅行建议和信息"
      initialStep: check-weather
      steps:
        - id: check-weather
          name: "检查天气"
          agent: travel-agent
          input:
            message: "请查询{{ workflow.input.destination }}的天气情况，并基于天气提供初步建议。"
          next: research-destination

        - id: research-destination
          name: "研究目的地"
          agent: research-agent
          input:
            message: "请搜索{{ workflow.input.destination }}的旅游信息，包括著名景点、文化和美食。"
          next: create-itinerary

        - id: create-itinerary
          name: "创建行程"
          agent: travel-agent
          input:
            message: |
              请根据以下信息，为前往{{ workflow.input.destination }}的{{ workflow.input.duration }}天行程制定详细计划：
              
              天气情况：{{ step.check-weather.result }}
              
              目的地信息：{{ step.research-destination.result }}
              
              预算要求：{{ workflow.input.budget }}
          next: END

  # 网络定义
  - apiVersion: mastra/v1
    kind: Network
    metadata:
      name: personal-assistant-network
      namespace: default
    spec:
      id: personal-assistant-network
      name: "Personal Assistant Network"
      description: "个人助理网络，包含多个专业代理"
      instructions: "这是一个个人助理网络，包含多个专业领域的代理，能够帮助处理各种查询。"
      agents:
        - name: researcher
          ref: default.research-agent
        - name: mathematician
          ref: default.math-agent
        - name: travel-advisor
          ref: default.travel-agent
        - name: summarizer
          ref: default.summary-agent
      router:
        model:
          provider: openai
          name: gpt-4
        instructions: "根据用户的查询决定应该由哪个代理回答。数学问题交给mathematician，旅行问题交给travel-advisor，研究任务交给researcher，需要总结时使用summarizer。"
        maxSteps: 10
      state:
        persistence: true
        ttl: 3600 